# Notes:
# docker exec -it some-mongo bash
# docker log some-mongo
# docker run --rm --link mongodb:mongo -v /root:/backup mongo bash -c 'mongodump --out /backup --host mongo:27017'
# docker run --rm --link mongodb:mongo -v /root:/backup mongo bash -c 'mongorestore /backup --host mongo:27017'

version: '3.1'

services:

  mongodb:
    image: 'mongo'
    restart: 'always'
    container_name: ${CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - './db:/data/db'
      - './mongod.conf:/etc/mongod.conf'
      - './entrypoint:/docker-entrypoint-initdb.d'
    command:
      - '-f'
      - '/etc/mongod.conf'
    ports:
      - '${EXTERNAL_PORT}:27017' # This should be updated per deploy
    env_file:
      - './.env'