version: '3.1'

services:
  drupal:
    container_name: ${CONTAINER_NAME}
    image: drupal:8-apache
    ports:
      - ${PORT}:80
    volumes:
      # - /var/www/html/modules
      # - /var/www/html/profiles
      # - /var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - ./sites:/var/www/html/sites
    restart: always

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always