version: '3.1'

services:
  drupal:
    image: custom_d8
    build:
      context: ./
    ports:
      - ${PORT}:80
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./libraries:/var/www/html/libraries
      - ./profiles:/var/www/html/profiles
      - ./sites:/var/www/html/sites
      # Add anonymous volumes to exclude cache files
      #- /var/www/html/sites/default/files/css
      #- /var/www/html/sites/default/files/js
      #- /var/www/html/sites/default/files/php
    restart: always
